#include "SheepApp.h"
#include "Moose.h"
#include "AppFactory.h"

template<>
InputParameters validParams<SheepApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  return params;
}

SheepApp::SheepApp(const std::string & name, InputParameters parameters) :
    MooseApp(name, parameters)
{
  srand(processor_id());

  Moose::registerObjects(_factory);
  SheepApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  SheepApp::associateSyntax(_syntax, _action_factory);
}

SheepApp::~SheepApp()
{
}

// External entry point for dynamic application loading
extern "C" void SheepApp__registerApps() { SheepApp::registerApps(); }
void
SheepApp::registerApps()
{
  registerApp(SheepApp);
}

// External entry point for dynamic object registration
extern "C" void SheepApp__registerObjects(Factory & factory) { SheepApp::registerObjects(factory); }
void
SheepApp::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void SheepApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { SheepApp::associateSyntax(syntax, action_factory); }
void
SheepApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
